# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGU1MTFmNzAwMTY2ZGNmMWI5MTVjZDVlNjY0ODI0YmQyZmI4N2ZjMzRhOGFmODY2YzUwN2M4ODM4Y2IxZDBlZGVjOTk1MWNlMWNiZDlkMDcwYTI4ZDVlYzcwNzllZGNjNGRmYjNiMjViNjgzYjk1YmY1YzIwNTM1NzUwYTA0ZmQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
