# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWMwZjA1ODZiOWU1NzZkZDBlNmI2NzNjYmY5MWIwNWYyMjYzODFmOGRmZjllYzRmMmMwYWY0ZjFjYzI2NDA5OGM4YzM3YTc4ZGRkMzIwYmJlNTAxMWNlYmMxMDI4NmQyZjliY2RlYWMwOTAwMThiMThhMGQ2ZGE3NWYxMjAzYjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
